### ISSUE TITLE
Trace correlation is not working

### ISSUE THREAD

**Issue by drewcorlin1** [open-policy-agent/opa-envoy-plugin#681]
## Short description 
I'm using OPA as an external authorization service in my istio service mesh. I have OpenTelemetry distributed tracing configured, and I see "envoy.service.auth.v3.Authorization/Check" spans being emitted, but they are creating new trace IDs (and thus not correlated with the request that is initiating the authorization check). This is happening even though the `traceparent` header is being passed to OPA

## Expected behavior
I would expect the "envoy.service.auth.v3.Authorization/Check" span to use the trace ID that is a part of the traceparent header being passed to OPA.

## Additional context
* I'm using 1.2.0 (using the `openpolicyagent/opa:1.2.0-envoy-static` image)
* I'm setting `distributed_tracing.type=grpc` and `distributed_tracing.address=opentelemetry-collector.opentelemetry:4317` (pointed to the OTel collector running in my k8s cluster)
* Logs showing the traceparent being received by OPA but a different trace ID being logged in the access logs

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/3a9bd2e9-f3cf-44bf-a1cb-94eccfead4a7" />

<img width="1727" alt="Image" src="https://github.com/user-attachments/assets/9fb76584-a977-4c02-83bb-cece98f56b1a" />

**Comment by srenatus** [comment]
Thanks for the report. I've moved it to the 's repo.

**Comment by DrewCorlin** [comment]
I'd be happy to work on a fix for this if someone with more context confirms this is a bug and if so could help point me in the right direction of a fix

**Comment by tjons** [comment]
Hey @DrewCorlin - this indeed looks like an issue! It's hard to tell whether it's a bug in our side or potentially some misconfiguration without setting it up myself. Free free to take this issue, I'll assign it to you and reach out with any questions.

Some relevant code to start looking at:

- https://github.com/open-policy-agent/opa-envoy-plugin/pull/431 is the original PR that added support for trace propagation in opa-envoy-plugin
- https://github.com/open-policy-agent/opa-envoy-plugin/blob/main/test/e2e/distributedtracing/distributedtracing_test.go#L109 - This is where we test the trace propagation. Note that we're testing the `X-b3-*` headers here, not the W3C headers (`traceparent`) you mention... might be a clue there.

**Comment by DrewCorlin** [comment]
thank you! At first glance it looks like the TraceContext propogator (`propagation.TraceContext`) should be handling w3c headers properly (see [this line](https://github.com/open-policy-agent/opa-envoy-plugin/blob/main/internal/internal.go#L159)), but I'll try to prove that out with some tests/tinkering and let you know what I find or if I have any more questions

**Comment by drewcorlin1** [comment]
Actually I think this has to do with my setup of envoy as an external auth service 🤦. I'm using an envoy filter with the `type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz` typed_config. If I update that `grpc_service` config to have
```yaml
initial_metadata:
  - key: traceparent
    value: "%REQ(TRACEPARENT)%"
```

then the correlation works properly!

I should probably move away from the envoy filter to [istio's newer external authorization](https://istio.io/latest/docs/tasks/security/authorization/authz-custom/) but that's a task for another day. In the hopes that this helps someone else in the future here's my config 😄 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ext_authz
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            transport_api_version: V3
            status_on_error:
              code: ServiceUnavailable
            with_request_body: null
            grpc_service:
              google_grpc:
                target_uri: 127.0.0.1:9191
                stat_prefix: "ext_authz"
              timeout: 3s
              # Adding this bit got trace correlation working
              initial_metadata:
                - key: traceparent
                  value: "%REQ(TRACEPARENT)%"
```
