### ISSUE TITLE
help matching filterMetadata sent from Envoy in OPA

### ISSUE THREAD

**Issue by chrisraiskin** [open-policy-agent/opa-envoy-plugin#700]
Been at it for a few days now - any help would be greatly appreciated.

I'm having Envoy pass validated JWT payload data into the `ext_authz` filter with `metadata_context_namespaces` and `payload_in_metadata`.  This part seems to work because I can see my test JWT content in OPA logs:

```
[{"type":"string","value":"metadataContext"},{"type":"object","value":[[{"type":"string","value":"filterMetadata"},{"type":"object","value":[[{"type":"string","value":"envoy.filters.http.jwt_authn"},{"type":"object","value":[[{"type":"string","value":"verified_jwt"},{"type":"object","value":[[{"type":"string","value":"iat"},{"type":"number","value":1745249683}],[{"type":"string","value":"iss"},{"type":"string","value":"demo"}],[{"type":"string","value":"role"},{"type":"string","value":"admin"}],[{"type":"string","value":"sub"},{"type":"string","value":"1234567890"}]]}]]}]]}]]}]
```

Everything seems to look exactly as described in [OPA Envoy Primer](https://www.openpolicyagent.org/docs/latest/envoy-primer/)

I try to evaluate `role` with the value of "admin"  in my OPA policy.

NOTE:  I wish I could see my `print()` statements in OPA server logs in debug mode, but I'm limited to `- "--log-level=debug"` output.  I do see my `print()` statements when I run unit test with `opa test -v`

```
package envoy.authz.demo

import future.keywords.if

default allow := false

allow if {
	print("INPUT from Envoy: ", input)
	is_role_admin
}

is_role_admin if {
	jwt.role == "admin"
}

	jwt := input.attributes.metadataContext.filterMetadata["envoy.filters.http.jwt_authn"].verified_jwt
```

When I send my test request via Envoy, it always returns  403 Forbidden,  so I'm assuming my OPA policy never "allow"s.
When I run my OPA test simulating JWT input, they both pass just fine

```
test_admin_role_allowed if {
  demo.is_role_admin with input as {
    "attributes": {
      "metadataContext": {
        "filterMetadata": {
          "envoy.filters.http.jwt_authn": {
            "verified_jwt": {
              "role": "admin"
            }
          }
        }
      }
    }
  }
}

test_user_role_denied if {
  not demo.is_role_admin with input as {
    "attributes": {
      "metadataContext": {
        "filterMetadata": {
          "envoy.filters.http.jwt_authn": {
            "verified_jwt": {
              "role": "user"
            }
          }
        }
      }
    }
  }
}
```

My Envoy config seems to follow the Envoy primer example, unless I'm missing something obvious

```
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                      log_format:
                        text_format_source:
                          inline_string: |
                            [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" 
                            %RESPONSE_CODE% %RESPONSE_FLAGS% 
                            "%REQ(USER-AGENT)%" "%REQ(X-FORWARDED-FOR)%" 
                            %BYTES_RECEIVED% %BYTES_SENT% 
                            %DURATION% %RESPONSE_DURATION% %REQUEST_DURATION% 
                            "%REQ(AUTHORIZATION)%"
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: app_service
                http_filters:
                  - name: envoy.filters.http.jwt_authn
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
                      providers:
                        jwt_provider:
                          issuer: "demo"
                          audiences: []
                          forward: true
                          payload_in_metadata: verified_jwt
                          from_headers:
                            - name: Authorization
                              value_prefix: "Bearer "
                          local_jwks:
                            inline_string: >
                              {
                                "keys": [
                                  {
                                    "kty": "oct",
                                    "k": "bXktc2VjcmV0LWtleQ",
                                    "alg": "HS256",
                                    "kid": "my-key"
                                  }
                                ]
                              }
                      rules:
                        - match:
                            prefix: "/"
                          requires:
                            provider_name: jwt_provider

                  - name: envoy.filters.http.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      failure_mode_allow: false
                      with_request_body:
                        max_request_bytes: 131072
                        allow_partial_message: false
                      grpc_service:
                        google_grpc:
                          target_uri: "opa:9191"
                          stat_prefix: "ext_authz"
                        timeout: 0.5s
                      transport_api_version: V3
                      metadata_context_namespaces:
                        - envoy.filters.http.jwt_authn

                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: app_service
      connect_timeout: 0.25s
      type: logical_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: app_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: app
                      port_value: 3000

admin:
  access_log_path: "/tmp/admin_access.log"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

```

**Comment by chrisraiskin** [comment]
To rule out OPA or Envoy,  I created a permissive policy to just allow anything :

```
package envoy.authz.demo

import future.keywords.if

default allow := true

allow if {
	true
}
```

And I'm still getting 403 Forbidden from Envoy.

Looking at Envoy logs

- Envoy receives the test request, validates/parses JWT successfully
- Envoy makes a gRPC call to the `ext_authz` filter for authorization
- from OPA logs,  the OPA server does receive the JWT via metadata
- Envoy receives a gRPC status code 2 (which means UNKNOWN or internal error?) 
- Envoy responds with 403 Forbidden and logs  `ext_authz_error`

Here are the relevant lines

```
envoy  | [2025-04-22 04:13:58.047][20][debug][grpc] [source/common/grpc/google_async_client_impl.cc:379] Finish with grpc-status code 2
envoy  | [2025-04-22 04:13:58.047][20][debug][grpc] [source/common/grpc/google_async_client_impl.cc:224] notifyRemoteClose 2 undefined decision
envoy  | [2025-04-22 04:13:58.047][20][debug][http] [source/common/http/filter_manager.cc:1065] [Tags: "ConnectionId":"0","StreamId":"1934679758762206735"] Sending local reply with details ext_authz_error
envoy  | [2025-04-22 04:13:58.047][20][debug][http] [source/common/http/conn_manager_impl.cc:1869] [Tags: "ConnectionId":"0","StreamId":"1934679758762206735"] encoding headers via codec (end_stream=true):
envoy  | ':status', '403'
envoy  | 'date', 'Tue, 22 Apr 2025 04:13:57 GMT'
envoy  | 'server', 'envoy'
```


Full Envoy log for the transaction

```
envoy  | [2025-04-22 04:13:58.040][20][debug][conn_handler] [source/common/listener_manager/active_tcp_listener.cc:160] [Tags: "ConnectionId":"0"] new connection from 192.168.65.1:31257
envoy  | [2025-04-22 04:13:58.040][20][debug][http] [source/common/http/conn_manager_impl.cc:393] [Tags: "ConnectionId":"0"] new stream
envoy  | [2025-04-22 04:13:58.041][20][debug][http] [source/common/http/conn_manager_impl.cc:1192] [Tags: "ConnectionId":"0","StreamId":"1934679758762206735"] request headers complete (end_stream=true):
envoy  | ':authority', 'localhost:8080'
envoy  | ':path', '/demo'
envoy  | ':method', 'GET'
envoy  | 'user-agent', 'curl/8.7.1'
envoy  | 'accept', '*/*'
envoy  | 'authorization', 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im15LWtleSJ9.eyJpc3MiOiJkZW1vIiwic3ViIjoiMTIzNDU2Nzg5MCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NTI0OTY4M30.-iTritqEQ9j3Q2G2uOQIAsTw2nPRQN2clN8qfifmfsc'
envoy  |
envoy  | [2025-04-22 04:13:58.041][20][debug][http] [source/common/http/conn_manager_impl.cc:1175] [Tags: "ConnectionId":"0","StreamId":"1934679758762206735"] request end stream
envoy  | [2025-04-22 04:13:58.041][20][debug][connection] [./source/common/network/connection_impl.h:98] [Tags: "ConnectionId":"0"] current connecting state: false
envoy  | [2025-04-22 04:13:58.041][20][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:159] Called Filter : setDecoderFilterCallbacks
envoy  | [2025-04-22 04:13:58.042][20][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:53] Called Filter : decodeHeaders
envoy  | [2025-04-22 04:13:58.042][20][debug][jwt] [source/extensions/filters/http/jwt_authn/matcher.cc:71] Prefix requirement '/' matched.
envoy  | [2025-04-22 04:13:58.042][20][debug][jwt] [source/extensions/filters/http/jwt_authn/extractor.cc:255] extract authorizationBearer
envoy  | [2025-04-22 04:13:58.042][20][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:162] jwt_provider: JWT authentication starts (allow_failed=false), tokens size=1
envoy  | [2025-04-22 04:13:58.042][20][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:173] jwt_provider: startVerify: tokens size 1
envoy  | [2025-04-22 04:13:58.042][20][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:191] jwt_provider: Parse Jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im15LWtleSJ9.eyJpc3MiOiJkZW1vIiwic3ViIjoiMTIzNDU2Nzg5MCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NTI0OTY4M30.-iTritqEQ9j3Q2G2uOQIAsTw2nPRQN2clN8qfifmfsc
envoy  | [2025-04-22 04:13:58.042][20][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:202] jwt_provider: Verifying JWT token of issuer demo
envoy  | [2025-04-22 04:13:58.042][20][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:428] jwt_provider: JWT token verification completed with: OK
envoy  | [2025-04-22 04:13:58.042][20][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:111] Jwt authentication completed with: OK
envoy  | [2025-04-22T04:13:58.040Z] "GET /demo HTTP/1.1"
envoy  | 403 UAEX
envoy  | "curl/8.7.1" "-"
envoy  | 0 0
envoy  | 6 - 0
envoy  | "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im15LWtleSJ9.eyJpc3MiOiJkZW1vIiwic3ViIjoiMTIzNDU2Nzg5MCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NTI0OTY4M30.-iTritqEQ9j3Q2G2uOQIAsTw2nPRQN2clN8qfifmfsc"
envoy  | [2025-04-22 04:13:58.047][20][debug][grpc] [source/common/grpc/google_async_client_impl.cc:379] Finish with grpc-status code 2
envoy  | [2025-04-22 04:13:58.047][20][debug][grpc] [source/common/grpc/google_async_client_impl.cc:224] notifyRemoteClose 2 undefined decision
envoy  | [2025-04-22 04:13:58.047][20][debug][http] [source/common/http/filter_manager.cc:1065] [Tags: "ConnectionId":"0","StreamId":"1934679758762206735"] Sending local reply with details ext_authz_error
envoy  | [2025-04-22 04:13:58.047][20][debug][http] [source/common/http/conn_manager_impl.cc:1869] [Tags: "ConnectionId":"0","StreamId":"1934679758762206735"] encoding headers via codec (end_stream=true):
envoy  | ':status', '403'
envoy  | 'date', 'Tue, 22 Apr 2025 04:13:57 GMT'
envoy  | 'server', 'envoy'
envoy  |
envoy  | [2025-04-22 04:13:58.047][20][debug][http] [source/common/http/conn_manager_impl.cc:1974] [Tags: "ConnectionId":"0","StreamId":"1934679758762206735"] Codec completed encoding stream.
```

**Comment by srenatus** [comment]
Can you enable reflection in the OPA config and use grpcurl to send an empty request to the relevant ext_authz API of opa-envoy-plugin?

**Comment by chrisraiskin** [comment]
Enabled reflection in my docker-compose `opa run`

```
  opa:
    image: opa-envoy:v0.43.0-arm64
    container_name: opa
    command:
      - "run"
      - "--log-level=debug"
      - "--log-format=json-pretty"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--set=plugins.envoy_ext_authz_grpc.enabled=true"
      - "--set=plugins.envoy_ext_authz_grpc.addr=:9191"
      - "--set=decision_logs.console=true"
      - "--set=plugins.envoy_ext_authz_grpc.enable-reflection=true"
      - "--skip-version-check"
      - "--watch"
      - "/policies"
    volumes:
      - ./opa/policies:/policies:ro
    working_dir: /policies
    ports:
      - "8181:8181"  # Optional: OPA REST API for testing
      - "9191:9191"  # Required: Envoy gRPC calls
    networks:
      - demo_net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8181/health?plugins"]
      interval: 5s
      timeout: 3s
      retries: 10
```

Ran a few test requests against the gRPC endpoint

```
$ grpcurl -plaintext localhost:9191 list envoy.service.auth.v3.Authorization

envoy.service.auth.v3.Authorization.Check

$ grpcurl -plaintext localhost:9191 describe envoy.service.auth.v3.Authorization.Check

envoy.service.auth.v3.Authorization.Check is a method:
rpc Check ( .envoy.service.auth.v3.CheckRequest ) returns ( .envoy.service.auth.v3.CheckResponse );

$ grpcurl -plaintext -d '{}' localhost:9191 envoy.service.auth.v3.Authorization/Check
ERROR:
  Code: Unknown
  Message: undefined decision

```

Next, I made sure I matched the package in my OPA policy to match the default path `/envoy/authz/allow`, and with that I got a better response to my empty body request

```
$ grpcurl -plaintext -d '{}' localhost:9191 envoy.service.auth.v3.Authorization/Check
{
  "status": {}
}
```

and finally,  I got 502 Bad Gateway for my test "resource server" request to Envoy (that's supposed to be routed on "allow") and after some googling i realized i had `http2_protocol_options: {}` in  my `clusters` of the envoy config.
Once I changed that to `http` (HTTP/1.1)  I got the request I expected.

Thanks for your help @srenatus !

Quick question:  is there any way to get  my OPA policy rules to write `print()` statements to the OPA server log?
I can see those statements when I run tests, but I would be really helpful to be able to see it at runtime on the server!

Thanks!
